version: "3.8"
services:
  airflow:
    build: 
      context: ./airflow
      # Args based on Airflow image
      args:
        INSTALL_MYSQL_CLIENT: "False"
        INSTALL_MSSQL_CLIENT: "False"
    # Environment variables based on Airflow doc
    # (https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#)
    env_file: ./.env  
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/temp:/opt/airflow/temp
      - ./data:/data
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
  
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: warehouse
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow", "-d", "warehouse"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    ports:
      - "5432:5432"